export interface LanguageRegistryEntry {
  name: string;
  detail: string;
  documentation: string;
  fields?: string[];
}

export interface LanguageRegistry {
  commands: LanguageRegistryEntry[];
  constructors: LanguageRegistryEntry[];
  enums: LanguageRegistryEntry[];
  fields: LanguageRegistryEntry[];
}

export const LANGUAGE_REGISTRY: LanguageRegistry = {
  commands: [
    entry(
      "define.package.manifest",
      "package manifest",
      "Defines one native IDEL package.",
      ["version", "summary", "license", "homepage", "repository", "source_revision"],
    ),
    entry(
      "define.repository.catalog",
      "repository catalog",
      "Defines governed package, source, container, or artifact providers.",
    ),
    entry(
      "register.repository.provider",
      "repository provider",
      "Registers a provider and its ecosystem-preserving adapter.",
      ["kind", "endpoint", "adapter"],
    ),
    entry(
      "define.project.application",
      "universal project",
      "Defines governed dependencies and resources for an application.",
    ),
    entry("export.intent", "package export", "Exports an IDEL intent.", ["source"]),
    entry("export.schema", "package export", "Exports an IDEL schema.", ["source"]),
    entry("export.policy", "package export", "Exports an IDEL policy.", ["source"]),
    entry("export.profile", "package export", "Exports an IDEL profile.", ["source"]),
    entry("export.wasm", "package export", "Exports a WASM entry point.", ["source"]),
    entry(
      "depend.package",
      "IDEL dependency",
      "Declares a native IDEL runtime dependency.",
      ["version"],
    ),
    entry(
      "depend.package.external",
      "external dependency",
      "Declares an external ecosystem package by purl.",
      ["ecosystem", "coordinate", "repository", "purpose", "version"],
    ),
    entry(
      "depend.package.idel",
      "native dependency",
      "Declares a digest-governed IDEL package.",
      ["coordinate", "integrity"],
    ),
    entry(
      "depend.source.repository",
      "source dependency",
      "Declares a Git source dependency pinned by the lockfile.",
      ["coordinate", "revision", "subpath"],
    ),
    entry(
      "depend.artifact.remote",
      "remote artifact",
      "Declares integrity-bound remote content.",
      ["source", "integrity", "media_type"],
    ),
    entry(
      "use.container.image",
      "OCI image",
      "Uses an immutable OCI/NexRun container image.",
      ["coordinate"],
    ),
    entry(
      "configure.runtime.engine",
      "runtime engine",
      "Configures a package runtime engine and governed limits.",
      ["version", "trust", "entry_point", "limit.cpu", "limit.memory"],
    ),
    entry(
      "permit.data.resource",
      "data capability",
      "Declares explicit data actions and fields.",
      ["actions", "fields"],
    ),
    entry(
      "permit.network.connect",
      "network capability",
      "Declares an outbound network capability.",
      ["protocol", "host", "port"],
    ),
    entry(
      "authorize.publisher.namespace",
      "publisher authority",
      "Binds package publication to IDEL Key authority.",
      ["authority", "required_approvals"],
    ),
    entry(
      "require.evidence.release",
      "release evidence",
      "Requires signature, provenance, SBOM, and conformance evidence.",
      ["signature", "provenance", "sbom", "conformance"],
    ),
    entry(
      "lock.external.package",
      "locked external package",
      "Records an exact ecosystem artifact and adapter.",
    ),
    entry(
      "lock.source.repository",
      "locked source repository",
      "Records an immutable Git commit and tree digest.",
    ),
    entry(
      "lock.package",
      "locked IDEL package",
      "Records an immutable native IDEL package.",
    ),
    entry(
      "define.proxy.gateway",
      "IDELProxy gateway",
      "Defines the authoritative listeners, redirects, routes, backends, policy, authority, and evidence contract for one IDELProxy gateway.",
    ),
    entry("use.proxy.provider", "proxy provider", "Selects the explicitly admitted IDELProxy data-plane provider.", ["kind"]),
    entry("listen.proxy.endpoint", "proxy listener", "Declares an HTTP, HTTPS, TCP, or TLS-pass-through listener.", ["address", "port", "protocol", "protocols", "certificate", "max_connections"]),
    entry("redirect.http.request", "HTTP redirect", "Declares a typed redirect before route selection.", ["from", "status", "enabled"]),
    entry("configure.redirect.destination", "redirect destination", "Builds a redirect Location from typed request components or literals.", ["scheme", "host", "path", "query"]),
    entry("match.http.host", "host match", "Matches an explicit list of HTTP hosts.", ["values"]),
    entry("match.http.path", "path match", "Matches an HTTP path prefix.", ["prefix"]),
    entry("match.http.scheme", "scheme match", "Matches the request scheme.", ["value"]),
    entry("define.proxy.backend", "proxy backend", "Defines endpoint discovery, balancing, health, capacity, and failover.", ["max_connections"]),
    entry("add.backend.server", "backend server", "Adds a weighted primary or standby endpoint.", ["endpoint", "weight", "tls", "sni", "role"]),
    entry("discover.backend.service", "backend discovery", "Discovers a typed NexRun service through its governed service name.", ["source", "port", "tls", "sni"]),
    entry("balance.backend.traffic", "load balancing", "Selects round-robin, weighted, least-load, source-IP, or consistent-hash balancing.", ["algorithm", "key"]),
    entry("check.backend.health", "backend health", "Configures active TCP, HTTP, or HTTPS health checks.", ["protocol", "path", "interval", "timeout", "unhealthy_after", "healthy_after"]),
    entry("configure.backend.failover", "backend failover", "Controls delayed standby activation and return to healthy primaries.", ["activate_standby_after", "return_to_primary"]),
    entry("route.http.request", "HTTP route", "Routes an HTTP request to one backend.", ["listener", "target", "retries", "max_body_bytes"]),
    entry("route.tcp.connection", "TCP route", "Routes a TCP or TLS-pass-through connection.", ["listener", "target"]),
    entry("split.http.traffic", "weighted HTTP split", "Splits matching HTTP traffic across weighted destinations.", ["listener", "retries", "max_body_bytes"]),
    entry("forward.http.backend", "backend forwarding", "Forwards a route to a named backend.", ["target"]),
    entry("destination.http.backend", "weighted destination", "Adds one backend to a canary or traffic split.", ["backend", "weight"]),
    entry("configure.http.timeout", "HTTP timeouts", "Sets connect, request, and idle timeout policy.", ["connect", "request", "idle"]),
    entry("limit.http.requests", "request rate limit", "Sets the per-source request rate and burst.", ["requests_per_second", "burst"]),
    entry("require.proxy.authority", "proxy authority", "Requires a signing authority for compiled proxy generations.", ["issuer", "required"]),
    entry("require.evidence.proxy", "proxy evidence", "Requires configuration, route-change, and rollback evidence.", ["configuration", "route_changes", "rollback"]),
  ],
  constructors: [
    entry("semver", "semantic version", "Constructs an exact Semantic Version."),
    entry("range", "version range", "Constructs an ecosystem version range."),
    entry("spdx", "SPDX expression", "Constructs an SPDX license expression."),
    entry("uri", "URI", "Constructs a validated URI."),
    entry("git", "Git coordinate", "Constructs a Git repository coordinate."),
    entry("commit", "Git commit", "Constructs an immutable Git commit identifier."),
    entry("path", "contained path", "Constructs a workspace-contained path."),
    entry("package", "adapter package", "Constructs a package and optional range reference."),
    entry("purl", "package URL", "Constructs an ECMA-427 package URL."),
    entry("repository", "repository reference", "References a registered repository provider."),
    entry("idel", "IDEL coordinate", "Constructs a native IDEL package coordinate."),
    entry("oci", "OCI coordinate", "Constructs an OCI image coordinate."),
    entry("file", "local artifact", "Constructs a workspace or local artifact reference."),
    entry("service", "service reference", "Constructs a governed service reference."),
    entry("database", "database reference", "Constructs a governed database reference."),
    entry("secret", "secret reference", "Constructs an authority-controlled secret reference."),
    entry("evidence", "evidence reference", "Constructs an OpenLogs evidence reference."),
    entry("idelkey", "IDEL Key authority", "Constructs an IDEL Key authority reference."),
    entry("digest", "content digest", "Constructs an algorithm-qualified digest."),
    entry("duration", "duration", "Constructs a normalized duration."),
    entry("bytes", "byte quantity", "Constructs a normalized byte quantity."),
    entry("instant", "timestamp", "Constructs an RFC 3339 instant."),
    entry("ip", "IP address", "Constructs a listener IP address."),
    entry("address", "network endpoint", "Constructs a DNS-or-IP host and port."),
    entry("endpoint", "listener reference", "References a named proxy listener."),
    entry("backend", "backend reference", "References a named proxy backend."),
    entry("nexrun", "NexRun service", "Constructs a service://namespace/name discovery source."),
    entry("percent", "traffic percentage", "Constructs an integer traffic percentage."),
    entry("request_header", "request header hash key", "Uses a request header as a consistent-hash key."),
    entry("request_cookie", "request cookie hash key", "Uses a request cookie as a consistent-hash key."),
    entry("replace_prefix", "path replacement", "Replaces a matching request-path prefix in a redirect."),
  ],
  enums: [
    entry("required", "requirement", "The value or evidence is required."),
    entry("optional", "requirement", "The value or evidence is optional."),
    entry("forbidden", "requirement", "The value or evidence is forbidden."),
    entry("builtin", "adapter", "Use the built-in native IDEL adapter."),
    entry("trust.l0.declarative", "trust level", "Pure declarative content."),
    entry("trust.l1.portable", "trust level", "Portable sandboxed code."),
    entry("trust.l2.connected", "trust level", "Mediated provider or network access."),
    entry("trust.l3.native", "trust level", "Native executable integration."),
    entry("trust.l4.system", "trust level", "Host or security-root integration."),
    entry("repository.npm", "repository kind", "npm-compatible registry."),
    entry("repository.maven", "repository kind", "Maven-compatible repository."),
    entry("repository.git", "repository kind", "Git source host."),
    entry("repository.oci", "repository kind", "OCI distribution registry."),
    entry("repository.idel", "repository kind", "Native IDEL package registry."),
    entry("ecosystem.npm", "ecosystem", "npm dependency semantics."),
    entry("ecosystem.maven", "ecosystem", "Maven dependency semantics."),
    entry("dependency.runtime", "dependency purpose", "Runtime dependency."),
    entry("dependency.development", "dependency purpose", "Development dependency."),
    entry("network.tcp", "network protocol", "TCP network transport."),
    entry("provider.native", "proxy provider", "Use the native IDELProxy data plane."),
    entry("protocol.http1", "listener protocol", "Accept HTTP/1.1."),
    entry("protocol.http2", "listener protocol", "Accept HTTP/2."),
    entry("protocol.https", "listener protocol", "Terminate HTTPS."),
    entry("protocol.tcp", "listener protocol", "Proxy TCP."),
    entry("protocol.tls_passthrough", "listener protocol", "Pass TLS through without termination."),
    entry("balance.round_robin", "balance algorithm", "Cycle evenly through healthy endpoints."),
    entry("balance.weighted_round_robin", "balance algorithm", "Cycle according to endpoint weights."),
    entry("balance.least_connections", "balance algorithm", "Choose the endpoint with the fewest active connections."),
    entry("balance.least_requests", "balance algorithm", "Choose the endpoint with the fewest observed requests."),
    entry("balance.source_ip_hash", "balance algorithm", "Affinitize by source IP."),
    entry("balance.consistent_hash", "balance algorithm", "Affinitize by a typed header, cookie, or source-IP key."),
    entry("backend.primary", "backend role", "Use the endpoint while it is healthy."),
    entry("backend.standby", "backend role", "Use the endpoint after the failover delay."),
    entry("failover.when_healthy", "failover return", "Return traffic to healthy primary endpoints."),
    entry("request.scheme", "request component", "Reuse the request scheme."),
    entry("request.host", "request component", "Reuse the request host."),
    entry("request.path", "request component", "Reuse the request path."),
    entry("request.query", "request component", "Preserve the request query."),
    entry("request.source_ip", "request hash key", "Use the source IP as a hash key."),
    entry("http.status.moved_permanently", "HTTP status", "Use HTTP 301."),
    entry("http.status.found", "HTTP status", "Use HTTP 302."),
    entry("http.status.temporary_redirect", "HTTP status", "Use HTTP 307."),
    entry("http.status.permanent_redirect", "HTTP status", "Use HTTP 308."),
  ],
  fields: [
    entry("version", "field", "Exact version or typed version range."),
    entry("summary", "field", "Human-readable summary."),
    entry("license", "field", "SPDX license expression."),
    entry("required_approvals", "field", "Required authority approval count."),
    entry("read_only_root", "field", "Whether the root filesystem is read-only."),
    entry("memory_limit", "field", "Typed memory limit."),
    entry("endpoint", "field", "Typed provider endpoint."),
    entry("adapter", "field", "Ecosystem adapter reference."),
    entry("coordinate", "field", "Typed resource coordinate."),
    entry("integrity", "field", "Algorithm-qualified content digest."),
    entry("repository", "field", "Repository or source reference."),
    entry("purpose", "field", "Dependency purpose."),
    entry("source_revision", "field", "Immutable source revision."),
    entry("media_type", "field", "Registered artifact media type."),
    entry("address", "field", "Typed listener or upstream address."),
    entry("port", "field", "Network port."),
    entry("protocol", "field", "Typed network protocol."),
    entry("protocols", "field", "Supported application protocols."),
    entry("certificate", "field", "Secret reference for TLS termination."),
    entry("max_connections", "field", "Maximum admitted connections."),
    entry("from", "field", "Source listener reference."),
    entry("status", "field", "Typed HTTP redirect status."),
    entry("enabled", "field", "Explicit signed feature activation state."),
    entry("scheme", "field", "Redirect scheme component."),
    entry("host", "field", "HTTP host or redirect host component."),
    entry("path", "field", "HTTP or redirect path."),
    entry("query", "field", "Redirect query policy."),
    entry("values", "field", "Typed list of match values."),
    entry("prefix", "field", "Path prefix."),
    entry("source", "field", "Typed discovery source."),
    entry("weight", "field", "Endpoint weight or traffic percentage."),
    entry("tls", "field", "Whether the upstream uses TLS."),
    entry("sni", "field", "TLS server name."),
    entry("role", "field", "Primary or standby endpoint role."),
    entry("algorithm", "field", "Load-balancing algorithm."),
    entry("key", "field", "Consistent-hash request key."),
    entry("interval", "field", "Health-check interval."),
    entry("timeout", "field", "Health-check timeout."),
    entry("unhealthy_after", "field", "Failures required to mark unhealthy."),
    entry("healthy_after", "field", "Successes required to mark healthy."),
    entry("activate_standby_after", "field", "Delay before standby activation."),
    entry("return_to_primary", "field", "Primary recovery policy."),
    entry("listener", "field", "Named listener reference."),
    entry("target", "field", "Named backend reference."),
    entry("retries", "field", "Idempotent retry count."),
    entry("max_body_bytes", "field", "Maximum buffered request body."),
    entry("connect", "field", "Upstream connection timeout."),
    entry("request", "field", "Upstream request timeout."),
    entry("idle", "field", "Idle timeout."),
    entry("requests_per_second", "field", "Per-source request rate."),
    entry("burst", "field", "Rate-limit burst capacity."),
    entry("issuer", "field", "Required signing authority."),
    entry("configuration", "field", "Configuration evidence requirement."),
    entry("route_changes", "field", "Route-change evidence requirement."),
    entry("rollback", "field", "Rollback evidence requirement."),
  ],
};

function entry(
  name: string,
  detail: string,
  documentation: string,
  fields?: string[],
): LanguageRegistryEntry {
  return {
    name,
    detail,
    documentation,
    ...(fields === undefined ? {} : { fields }),
  };
}
